### ISSUE TITLE
ストーリー: 眠気やわき見の兆候を表示できる

### ISSUE THREAD

**Issue by moritama312** [sensetime-jp/dms-demo#18]
## 概要

中国デモのDrawsinessやDistractionは3レベルで表現されていて、
レベル1に達するまで異常を検出できない。
メーターの分解能を上げ、レベル1に達しない些細な兆候を表示できるようにしたい。

## デモ手順
 1. デモを起動する
 2. Drawsinessについて、異常状態が続くとメーターに素早く反映される様子を確認する
 3. Distractionについて、異常状態が続くとメーターに素早く反映される様子を確認する
 
## タスク
* [x] 付箋を貼り付ける
* [x] 概要、デモ手順を記述する
* [x] issue #32 SDK側のDrowsiness APIを設計する
* [x] issue #33 SDK側のDistraction APIを設計する
* [x] issue #34 SDK側のDrowsiness APIを実装する
* [x] issue #35 SDK側のDistraction APIを実装する
* [x] issue #36 高分解能APIを用いてDrawsiness/Distractionメーターを実装する 
* [x] スプリントレビューでデモを実施する

**Comment by moritama312** [comment]
デモしました。クローズします。
